//! Embed the consumer kit's skills into the binary at compile time.
//!
//! `dec:skills-served`, accepted 2026-07-25 on Anthony's word after his
//! brother's feedback: *"you wouldn't need to change anything in your repo
//! again and updates would be confined to the reflow package."*
//!
//! Until now the skills reached a project by being **copied** there by
//! `reflow2_init.py`, which meant every upgrade rewrote thirty-odd files in a
//! repo that has nothing to do with reflow2's release — and, worse, that an
//! installed kit silently froze while reflow2 moved. reflow2's own kit manifest
//! sat **four releases stale** and nothing noticed, which is the drift class
//! this project exists to catch, arriving in the one place nobody was watching.
//!
//! The fix is the one this project keeps arriving at: **remove the copy, and
//! the drift has nowhere to live.** Reading the skills off disk at runtime
//! would have re-created the same problem one layer down (which directory?
//! installed when?), so they are compiled *into* the binary. The served
//! catalogue and the running server are then the same artifact, and "the skills
//! are stale" stops being a state the system can be in.
//!
//! `cargo:rerun-if-changed` on the kit means editing a SKILL.md rebuilds the
//! server — so the gate that checks the served surface is checking the source.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let kit = kit_dir();
    println!("cargo:rerun-if-changed={}", kit.display());

    let mut skills: Vec<(String, String, String, PathBuf)> = Vec::new();
    let entries = std::fs::read_dir(&kit).unwrap_or_else(|e| {
        panic!(
            "reflow2: cannot read the skill kit at {}: {e}",
            kit.display()
        )
    });
    for entry in entries {
        let dir = entry.expect("readable dir entry").path();
        if !dir.is_dir() {
            continue;
        }
        let file = dir.join("SKILL.md");
        if !file.exists() {
            // Loud: a skill directory with no SKILL.md is a skill that would
            // silently never load, which is exactly the failure the installer
            // already refuses to ship.
            panic!("reflow2: {} has no SKILL.md", dir.display());
        }
        println!("cargo:rerun-if-changed={}", file.display());
        let text = std::fs::read_to_string(&file).expect("readable SKILL.md");
        let (name, description) = frontmatter(&text, &file);
        let dir_name = dir
            .file_name()
            .and_then(|s| s.to_str())
            .expect("utf-8 dir name")
            .to_string();
        assert_eq!(
            name, dir_name,
            "reflow2: skill name {name:?} does not match its directory {dir_name:?} — a harness \
             would ignore it silently"
        );
        skills.push((name, description, dir_name, file));
    }
    assert!(
        !skills.is_empty(),
        "reflow2: no skills found under {} — the server would advertise an empty catalogue",
        kit.display()
    );
    skills.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::from(
        "// @generated by build.rs from getting-started/skills — do not edit.\n\
         pub static SKILLS: &[EmbeddedSkill] = &[\n",
    );
    for (name, description, _, file) in &skills {
        writeln!(
            out,
            "    EmbeddedSkill {{ name: {name:?}, description: {description:?}, \
             body: include_str!({:?}) }},",
            file.display().to_string()
        )
        .expect("write to String");
    }
    out.push_str("];\n");

    // The working instructions travel the same way and for the same reason
    // (req:thin-install): what a consumer project holds is a stable pointer,
    // and everything that moves between releases is served. Embedding it here
    // means the served text and the running server are one artifact.
    let instructions = kit.parent().expect("kit has a parent").join("AGENTS.md");
    assert!(
        instructions.exists(),
        "reflow2: {} is missing — the server would serve no instructions",
        instructions.display()
    );
    println!("cargo:rerun-if-changed={}", instructions.display());
    out.push_str(&format!(
        "\npub static INSTRUCTIONS: &str = include_str!({:?});\n",
        instructions.display().to_string()
    ));

    let dest =
        PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("skills_generated.rs");
    std::fs::write(&dest, out).expect("write generated skills");
}

/// The kit lives at the repo root, beside the crates.
fn kit_dir() -> PathBuf {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(Path::parent)
        .expect("crate is two levels under the repo root")
        .join("getting-started")
        .join("skills")
}

/// `name` and `description` out of the YAML frontmatter every harness agrees on.
///
/// Deliberately not a YAML dependency: these two fields are flat scalars in
/// every skill, and a build script that pulled a parser in would be paying for
/// generality nothing uses. A malformed field fails the build rather than
/// producing a skill that loads with no description — the field agents match on.
fn frontmatter(text: &str, file: &Path) -> (String, String) {
    let body = text
        .strip_prefix("---\n")
        .and_then(|rest| rest.split_once("\n---\n"))
        .map(|(fm, _)| fm)
        .unwrap_or_else(|| panic!("reflow2: {} has no YAML frontmatter", file.display()));

    let mut name = None;
    let mut description = None;
    for line in body.lines() {
        if let Some(v) = line.strip_prefix("name:") {
            name = Some(v.trim().trim_matches('"').to_string());
        } else if let Some(v) = line.strip_prefix("description:") {
            description = Some(v.trim().trim_matches('"').to_string());
        }
    }
    let name = name.unwrap_or_else(|| panic!("reflow2: {} has no name", file.display()));
    let description =
        description.unwrap_or_else(|| panic!("reflow2: {} has no description", file.display()));
    assert!(
        !description.is_empty(),
        "reflow2: {} has an empty description — agents match on it to decide whether to load the \
         skill at all",
        file.display()
    );
    (name, description)
}
